### ISSUE TITLE
When will vboxwebmgr support virtualbox-7.1?

### ISSUE THREAD

**Issue by sdany-g** [thedisbo1125/vboxwebmgr#4]
Hi：thedisbo1125
I used to use phpvirtualbox, but since php8.2, I have used vboxwebmgr, which is as good as phpvirtualbox. Now virtualbox-7.1 has been released, I wonder when it will be supported?
 Thanks!

**Comment by thedisbo1125** [comment]
Been messing around with other projects but when I saw 7.1 is available, I started getting a dev environment setup.  I'll try and get some testing done in the next month or so and put an updated version for 7.1 out.
Rich

**Comment by thedisbo1125** [comment]
Since I know someone else besides me is using it, I'll try and move it up the list of things to work on.  Main reason I did was as a learning experience and the company in Australia that took over phpvirtualbox seemed to have abandoned it during the pandemic.  I suspect they were using it and wanted to keep it going but due to cutbacks, didn't have personnel anymore for it.  I emailed them several times about it but never got a response back.

**Comment by sdany-g** [comment]
Thank you for providing the update! I'm glad to hear that you plan to continue maintaining and updating this project. I believe it will be greatly beneficial to many people.

Due to networking issues with Virtualbox-7.0 (I recently discovered that a setting in the network adapter driver needs to be disabled), I have been using Virtualbox-6.1. However, it seems that starting from Debian 12.6 with linux-image-6.1.0-21, Virtualbox-6.1 no longer works properly after installation. So when I saw Virtualbox-7.1 was released, I wanted to test whether it has improved the networking issues of Virtualbox-7.0 and if it performs better on the new system.

I hope you gain more knowledge and experience during this process. Thank you once again for your effort and dedication!

**Comment by thedisbo1125** [comment]
I have completed the majority of code changes to support 7.1, code is under branch virtualbox-7.1-testing.  I also fixed a couple other issues I found.  You can test it out whenever you get a chance.  Currently, selecting "Linked Clone" doesn't work.  If you find anything else, please document the steps you did and I'll see about recreating the problem and fix it.

**Comment by thedisbo1125** [comment]
Also, can you post info about the networking issue you found?  I only used bridged adapters on all my VMs, so maybe that why I haven't encountered it.  Also why I added "Network Interface Limits" under preferences.
At some point in the future, hope to change how the list of VMs is displayed so can show multiple servers at the same time (and allow for teleportation between hosts).

**Comment by sdany-g** [comment]
Network Issue Description:

The virtual machine and host are not using the same network interface—the download speed is normal, but the upload speed is very slow. I noticed this issue when I installed Samba on the host and accessed the shared directory from a virtual machine running Windows.

Later, I saw on the VirtualBox forum that others were experiencing the same issue, and it was suggested to disable the network card's "Large Send Offload" feature.

However, more recently, I encountered a different situation: with my main network card being an Intel 350  and the other a Realtek card, everything worked fine without changing the drivers.

This seems to be a problem with VirtualBox and probably doesn't have much to do with phpVirtualBox.

In a few days, I will test vboxwebmgr-virtualbox-7.1-testing to see how it performs with VirtualBox 7.1, and I'll get back to you with feedback.

Thank you!

**Comment by sdany-g** [comment]
Just installed VirtualBox 7.1.4, and the network issue in the Windows virtual machine is still the same as with version 7.0. It's necessary to disable the network adapter's "Large Send Offload".

**Comment by sdany-g** [comment]
I don't understand what network-related settings VirtualBox started to change from version 7.0, causing differences in network settings compared to version 6.1 and earlier. I'm not sure how much this impacts network performance.

**Comment by sdany-g** [comment]
7.1-003
1、VMs cannot be remotely connected to by RDP
2、Setting menu to show no 【ok】【cancel】

**Comment by thedisbo1125** [comment]
2 is fixed.  For RDP, what client are you using?  I use freerdp and it will prompt me for Domain and Password if not set in the RDP file.  Also, VirtualBox 7.1 generates a self signed certificate when you create a new VM and configures the RDP connection to use it.  FreeRDP doesn't trust the cert unless you specifically say to (see attached textfile).
[rdp.txt](https://github.com/user-attachments/files/17680653/rdp.txt)

**Comment by thedisbo1125** [comment]
I ended up creating my own CA, setup my PCs to trust it, and created a cert for all VMs to use.  Going to add the ability to change the cert on the "Remote Desktop" page at some point in the future.

**Comment by sdany-g** [comment]
> 2 is fixed. For RDP, what client are you using? I use freerdp and it will prompt me for Domain and Password if not set in the RDP file. Also, VirtualBox 7.1 generates a self signed certificate when you create a new VM and configures the RDP connection to use it. FreeRDP doesn't trust the cert unless you specifically say to (see attached textfile). [rdp.txt](https://github.com/user-attachments/files/17680653/rdp.txt)

I used the RDP that comes with Windows. The reason was found. The previous version did not see the menu option [Security Method], and the default was TLS. This caused the Win7 RDP connection to fail, but Win11 could connect. After changing TLS to RDP Win7 connection, it worked.

**Comment by thedisbo1125** [comment]
Gotcha, the security method setting was in previous versions of VirtualBox, but with 7.1, they made a specific call to set it, so I threw it in.

**Comment by thedisbo1125** [comment]
Going to close this issue.  Let me know if you find any other problems.

**Comment by sdany-g** [comment]
I have downloaded and used it, and I have not found any problems so far. Thank you very much for your strong support.
